name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
  
    - name: Make daily commit
      run: |
        echo "Daily commit" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit - $(date +'%Y-%m-%d')"
        git push
