name: Daily Commit

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set git config
      run: |
        git config --global user.name "Josh"
        git config --global user.email "joshuajpiluden@gmail.com"

    - name: Make daily commit
      run: |
        echo "Daily commit" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit - $(date +'%Y-%m-%d')"
        git push












  






